# -*- coding: utf-8 -*-
from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(445, 628)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(445, 628))
        MainWindow.setMaximumSize(QtCore.QSize(445, 628))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("nao.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QtCore.QSize(48, 48))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.WakeButton = QtGui.QPushButton(self.centralWidget)
        self.WakeButton.setGeometry(QtCore.QRect(340, 290, 60, 27))
        self.WakeButton.setAutoExclusive(False)
        self.WakeButton.setObjectName(_fromUtf8("WakeButton"))
        self.RestButton = QtGui.QPushButton(self.centralWidget)
        self.RestButton.setGeometry(QtCore.QRect(260, 290, 60, 27))
        self.RestButton.setObjectName(_fromUtf8("RestButton"))
        self.IPLabel = QtGui.QLabel(self.centralWidget)
        self.IPLabel.setGeometry(QtCore.QRect(10, 10, 91, 17))
        self.IPLabel.setObjectName(_fromUtf8("IPLabel"))
        self.PORTLabel = QtGui.QLabel(self.centralWidget)
        self.PORTLabel.setGeometry(QtCore.QRect(10, 70, 64, 17))
        self.PORTLabel.setObjectName(_fromUtf8("PORTLabel"))
        self.ConnectButton = QtGui.QPushButton(self.centralWidget)
        self.ConnectButton.setGeometry(QtCore.QRect(60, 130, 91, 27))
        self.ConnectButton.setObjectName(_fromUtf8("ConnectButton"))
        self.textIP = QtGui.QLineEdit(self.centralWidget)
        self.textIP.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.textIP.setObjectName(_fromUtf8("textIP"))
        self.textPORT = QtGui.QLineEdit(self.centralWidget)
        self.textPORT.setGeometry(QtCore.QRect(10, 90, 201, 31))
        self.textPORT.setObjectName(_fromUtf8("textPORT"))
        self.saludoButton = QtGui.QPushButton(self.centralWidget)
        self.saludoButton.setGeometry(QtCore.QRect(230, 130, 61, 27))
        self.saludoButton.setObjectName(_fromUtf8("saludoButton"))
        self.sayText = QtGui.QLineEdit(self.centralWidget)
        self.sayText.setGeometry(QtCore.QRect(10, 180, 201, 31))
        self.sayText.setObjectName(_fromUtf8("sayText"))
        self.sayButton = QtGui.QPushButton(self.centralWidget)
        self.sayButton.setGeometry(QtCore.QRect(60, 220, 91, 27))
        self.sayButton.setObjectName(_fromUtf8("sayButton"))
        self.pictureButton = QtGui.QPushButton(self.centralWidget)
        self.pictureButton.setGeometry(QtCore.QRect(290, 580, 141, 31))
        self.pictureButton.setObjectName(_fromUtf8("pictureButton"))
        self.frontButton = QtGui.QPushButton(self.centralWidget)
        self.frontButton.setGeometry(QtCore.QRect(289, 340, 81, 31))
        self.frontButton.setObjectName(_fromUtf8("frontButton"))
        self.sitButton = QtGui.QPushButton(self.centralWidget)
        self.sitButton.setGeometry(QtCore.QRect(289, 380, 81, 61))
        self.sitButton.setObjectName(_fromUtf8("sitButton"))
        self.backButton = QtGui.QPushButton(self.centralWidget)
        self.backButton.setGeometry(QtCore.QRect(289, 450, 81, 31))
        self.backButton.setObjectName(_fromUtf8("backButton"))
        self.rightButton = QtGui.QPushButton(self.centralWidget)
        self.rightButton.setGeometry(QtCore.QRect(379, 380, 31, 61))
        self.rightButton.setObjectName(_fromUtf8("rightButton"))
        self.leftButton = QtGui.QPushButton(self.centralWidget)
        self.leftButton.setGeometry(QtCore.QRect(249, 380, 31, 61))
        self.leftButton.setObjectName(_fromUtf8("leftButton"))
        self.USLabel = QtGui.QLabel(self.centralWidget)
        self.USLabel.setGeometry(QtCore.QRect(10, 260, 161, 17))
        self.USLabel.setObjectName(_fromUtf8("USLabel"))
        self.USLeftText = QtGui.QLineEdit(self.centralWidget)
        self.USLeftText.setGeometry(QtCore.QRect(10, 280, 91, 27))
        self.USLeftText.setObjectName(_fromUtf8("USLeftText"))
        self.USRightText = QtGui.QLineEdit(self.centralWidget)
        self.USRightText.setGeometry(QtCore.QRect(110, 280, 91, 27))
        self.USRightText.setObjectName(_fromUtf8("USRightText"))
        self.GyroLabel = QtGui.QLabel(self.centralWidget)
        self.GyroLabel.setGeometry(QtCore.QRect(10, 320, 81, 17))
        self.GyroLabel.setObjectName(_fromUtf8("GyroLabel"))
        self.GyroXtext = QtGui.QLineEdit(self.centralWidget)
        self.GyroXtext.setGeometry(QtCore.QRect(10, 340, 61, 27))
        self.GyroXtext.setObjectName(_fromUtf8("GyroXtext"))
        self.GyroYtext = QtGui.QLineEdit(self.centralWidget)
        self.GyroYtext.setGeometry(QtCore.QRect(80, 340, 61, 27))
        self.GyroYtext.setObjectName(_fromUtf8("GyroYtext"))
        self.animationlabel = QtGui.QLabel(self.centralWidget)
        self.animationlabel.setGeometry(QtCore.QRect(230, 110, 91, 20))
        self.animationlabel.setObjectName(_fromUtf8("animationlabel"))
        self.volumeSlider = phonon.Phonon.VolumeSlider(self.centralWidget)
        self.volumeSlider.setGeometry(QtCore.QRect(230, 82, 191, 21))
        self.volumeSlider.setMaximumVolume(100.0)
        self.volumeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.volumeSlider.setObjectName(_fromUtf8("volumeSlider"))
        self.AcceleLabel = QtGui.QLabel(self.centralWidget)
        self.AcceleLabel.setGeometry(QtCore.QRect(10, 380, 171, 16))
        self.AcceleLabel.setObjectName(_fromUtf8("AcceleLabel"))
        self.AccelXtext = QtGui.QLineEdit(self.centralWidget)
        self.AccelXtext.setGeometry(QtCore.QRect(10, 400, 61, 29))
        self.AccelXtext.setObjectName(_fromUtf8("AccelXtext"))
        self.AccelYtext = QtGui.QLineEdit(self.centralWidget)
        self.AccelYtext.setGeometry(QtCore.QRect(80, 400, 61, 29))
        self.AccelYtext.setObjectName(_fromUtf8("AccelYtext"))
        self.AccelZtext = QtGui.QLineEdit(self.centralWidget)
        self.AccelZtext.setGeometry(QtCore.QRect(150, 400, 61, 29))
        self.AccelZtext.setObjectName(_fromUtf8("AccelZtext"))
        self.vacuumButton = QtGui.QPushButton(self.centralWidget)
        self.vacuumButton.setGeometry(QtCore.QRect(300, 130, 61, 27))
        self.vacuumButton.setObjectName(_fromUtf8("vacuumButton"))
        self.musclesButton = QtGui.QPushButton(self.centralWidget)
        self.musclesButton.setGeometry(QtCore.QRect(230, 170, 61, 27))
        self.musclesButton.setObjectName(_fromUtf8("musclesButton"))
        self.avionButton = QtGui.QPushButton(self.centralWidget)
        self.avionButton.setGeometry(QtCore.QRect(300, 170, 61, 27))
        self.avionButton.setObjectName(_fromUtf8("r2d2Button"))
        self.flyingButton = QtGui.QPushButton(self.centralWidget)
        self.flyingButton.setGeometry(QtCore.QRect(370, 130, 61, 27))
        self.flyingButton.setObjectName(_fromUtf8("flyingButton"))
        self.kongButton = QtGui.QPushButton(self.centralWidget)
        self.kongButton.setGeometry(QtCore.QRect(370, 170, 61, 27))
        self.kongButton.setObjectName(_fromUtf8("kongButton"))
        self.nopeButton = QtGui.QPushButton(self.centralWidget)
        self.nopeButton.setGeometry(QtCore.QRect(230, 210, 61, 27))
        self.nopeButton.setObjectName(_fromUtf8("nopeButton"))
        self.yeahButton = QtGui.QPushButton(self.centralWidget)
        self.yeahButton.setGeometry(QtCore.QRect(370, 210, 61, 27))
        self.yeahButton.setObjectName(_fromUtf8("yeahButton"))
        self.rockButton = QtGui.QPushButton(self.centralWidget)
        self.rockButton.setGeometry(QtCore.QRect(300, 210, 61, 27))
        self.rockButton.setObjectName(_fromUtf8("rockButton"))
        self.hotspotButton = QtGui.QPushButton(self.centralWidget)
        self.hotspotButton.setGeometry(QtCore.QRect(290, 540, 141, 31))
        self.hotspotButton.setObjectName(_fromUtf8("hotspotButton"))
        self.turnFrButton = QtGui.QPushButton(self.centralWidget)
        self.turnFrButton.setGeometry(QtCore.QRect(380, 340, 31, 31))
        self.turnFrButton.setObjectName(_fromUtf8("turnFrButton"))
        self.turnFlButton = QtGui.QPushButton(self.centralWidget)
        self.turnFlButton.setGeometry(QtCore.QRect(250, 340, 31, 31))
        self.turnFlButton.setObjectName(_fromUtf8("turnFlButton"))
        self.turnBrButton = QtGui.QPushButton(self.centralWidget)
        self.turnBrButton.setGeometry(QtCore.QRect(380, 450, 31, 31))
        self.turnBrButton.setObjectName(_fromUtf8("turnBrButton"))
        self.turnBlButton = QtGui.QPushButton(self.centralWidget)
        self.turnBlButton.setGeometry(QtCore.QRect(250, 450, 31, 31))
        self.turnBlButton.setObjectName(_fromUtf8("turnBlButton"))
        self.AnySayLabel = QtGui.QLabel(self.centralWidget)
        self.AnySayLabel.setGeometry(QtCore.QRect(10, 480, 101, 16))
        self.AnySayLabel.setObjectName(_fromUtf8("AnySayLabel"))
        self.AniSayText = QtGui.QLineEdit(self.centralWidget)
        self.AniSayText.setGeometry(QtCore.QRect(10, 500, 201, 29))
        self.AniSayText.setToolTip(_fromUtf8(""))
        self.AniSayText.setObjectName(_fromUtf8("AniSayText"))
        self.explicandoButton = QtGui.QPushButton(self.centralWidget)
        self.explicandoButton.setGeometry(QtCore.QRect(230, 250, 61, 27))
        self.explicandoButton.setObjectName(_fromUtf8("explicandoButton"))
        self.excitedButton = QtGui.QPushButton(self.centralWidget)
        self.excitedButton.setGeometry(QtCore.QRect(370, 250, 61, 27))
        self.excitedButton.setObjectName(_fromUtf8("excitedButton"))
        self.calmDownButton = QtGui.QPushButton(self.centralWidget)
        self.calmDownButton.setGeometry(QtCore.QRect(300, 250, 61, 27))
        self.calmDownButton.setObjectName(_fromUtf8("calmDownButton"))
        self.autonoModeButton = QtGui.QPushButton(self.centralWidget)
        self.autonoModeButton.setGeometry(QtCore.QRect(290, 500, 141, 31))
        self.autonoModeButton.setObjectName(_fromUtf8("autonoModeButton"))
        self.AnySayButton = QtGui.QPushButton(self.centralWidget)
        self.AnySayButton.setGeometry(QtCore.QRect(120, 580, 88, 27))
        self.AnySayButton.setObjectName(_fromUtf8("AnySayButton"))
        self.readSensorButton = QtGui.QPushButton(self.centralWidget)
        self.readSensorButton.setGeometry(QtCore.QRect(60, 440, 88, 27))
        self.readSensorButton.setObjectName(_fromUtf8("readSensorButton"))
        self.BatteryLabel = QtGui.QLabel(self.centralWidget)
        self.BatteryLabel.setGeometry(QtCore.QRect(240, 10, 111, 16))
        self.BatteryLabel.setObjectName(_fromUtf8("BatteryLabel"))
        self.batteryText = QtGui.QLineEdit(self.centralWidget)
        self.batteryText.setGeometry(QtCore.QRect(240, 30, 91, 29))
        self.batteryText.setObjectName(_fromUtf8("batteryText"))
        self.batteryButton = QtGui.QPushButton(self.centralWidget)
        self.batteryButton.setGeometry(QtCore.QRect(350, 30, 88, 27))
        self.batteryButton.setObjectName(_fromUtf8("batteryButton"))
        self.comboBox = QtGui.QComboBox(self.centralWidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 540, 201, 27))
#Te vamos a extrañar Vani, de veritas
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.textIP, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.ConnectButton.click)
        QtCore.QObject.connect(self.sayText, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.sayButton.click)
        QtCore.QObject.connect(self.textPORT, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.ConnectButton.click)
        QtCore.QObject.connect(self.AniSayText, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.AnySayButton.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.sayButton, self.pictureButton)
        MainWindow.setTabOrder(self.pictureButton, self.saludoButton)
        MainWindow.setTabOrder(self.saludoButton, self.WakeButton)
        MainWindow.setTabOrder(self.WakeButton, self.sitButton)
        MainWindow.setTabOrder(self.sitButton, self.frontButton)
        MainWindow.setTabOrder(self.frontButton, self.textIP)
        MainWindow.setTabOrder(self.textIP, self.textPORT)
        MainWindow.setTabOrder(self.textPORT, self.ConnectButton)
        MainWindow.setTabOrder(self.ConnectButton, self.sayText)
        MainWindow.setTabOrder(self.sayText, self.RestButton)
        MainWindow.setTabOrder(self.RestButton, self.backButton)
        MainWindow.setTabOrder(self.backButton, self.rightButton)
        MainWindow.setTabOrder(self.rightButton, self.leftButton)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyNao", None))
        self.WakeButton.setText(_translate("MainWindow", "WakeUp", None))
        self.RestButton.setText(_translate("MainWindow", "Rest", None))
        self.IPLabel.setText(_translate("MainWindow", "Dirección IP", None))
        self.PORTLabel.setText(_translate("MainWindow", "Puerto", None))
        self.ConnectButton.setText(_translate("MainWindow", "Conectar", None))
        self.textIP.setToolTip(_translate("MainWindow", "<html><head/><body><p>Inserte la dirección IP del robot</p></body></html>", None))
        self.textIP.setText(_translate("MainWindow", "192.168.0.0.1", None))
        self.textPORT.setToolTip(_translate("MainWindow", "<html><head/><body><p>Escriba la dirección a la cual desea acceder</p></body></html>", None))
        self.textPORT.setText(_translate("MainWindow", "9559", None))
        self.saludoButton.setText(_translate("MainWindow", "Saludar", None))
        self.sayText.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ingrese un texto para que el robot lo diga</p></body></html>", None))
        self.sayText.setText(_translate("MainWindow", "Hola Padawan!", None))
        self.sayButton.setText(_translate("MainWindow", "Say!", None))
        self.pictureButton.setToolTip(_translate("MainWindow", "<html><head/><body><p>Presione para tomar una foto, las fotos son almacenadas dentro de la carpeta NaoSelfies</p></body></html>", None))
        self.pictureButton.setText(_translate("MainWindow", "Tomar Fotografía", None))
        self.frontButton.setText(_translate("MainWindow", "Front", None))
        self.sitButton.setText(_translate("MainWindow", "Sit", None))
        self.backButton.setText(_translate("MainWindow", "Back", None))
        self.rightButton.setText(_translate("MainWindow", "R", None))
        self.leftButton.setText(_translate("MainWindow", "L", None))
        self.USLabel.setText(_translate("MainWindow", "Sensores Ultrasónicos", None))
        self.GyroLabel.setText(_translate("MainWindow", "Giroscopio", None))
        self.animationlabel.setText(_translate("MainWindow", "Animaciones", None))
        self.AcceleLabel.setText(_translate("MainWindow", "Datos Del Acelerometro", None))
        self.vacuumButton.setText(_translate("MainWindow", "Vacuum", None))
        self.musclesButton.setText(_translate("MainWindow", "Muscles", None))
        self.avionButton.setText(_translate("MainWindow", "R2D2", None))
        self.flyingButton.setText(_translate("MainWindow", "Flying", None))
        self.kongButton.setText(_translate("MainWindow", "Kong", None))
        self.nopeButton.setText(_translate("MainWindow", "Nope", None))
        self.yeahButton.setText(_translate("MainWindow", "Dialogo", None))
        self.rockButton.setText(_translate("MainWindow", "Rock!", None))
        self.hotspotButton.setText(_translate("MainWindow", "Crear Hotspot", None))
        self.turnFrButton.setText(_translate("MainWindow", "FR", None))
        self.turnFlButton.setText(_translate("MainWindow", "FL", None))
        self.turnBrButton.setText(_translate("MainWindow", "BR", None))
        self.turnBlButton.setText(_translate("MainWindow", "BL", None))
        self.AnySayLabel.setText(_translate("MainWindow", "Animated Say", None))
        self.explicandoButton.setText(_translate("MainWindow", "Explain", None))
        self.excitedButton.setText(_translate("MainWindow", "Excited", None))
        self.calmDownButton.setText(_translate("MainWindow", "Cool", None))
        self.autonoModeButton.setText(_translate("MainWindow", "AutonoMode", None))
        self.AnySayButton.setText(_translate("MainWindow", "Say!", None))
        self.readSensorButton.setText(_translate("MainWindow", "ReadData", None))
        self.BatteryLabel.setText(_translate("MainWindow", "Battery Status", None))
        self.batteryButton.setText(_translate("MainWindow", "Check", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Contextual", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "BodyTalk_1", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "BodyTalk_2", None))
        self.comboBox.setItemText(3, _translate("MainWindow", "IDontKnow_1", None))
        self.comboBox.setItemText(4, _translate("MainWindow", "Me_1", None))
        self.comboBox.setItemText(5, _translate("MainWindow", "Me_2", None))
        self.comboBox.setItemText(6, _translate("MainWindow", "No_1", None))
        self.comboBox.setItemText(7, _translate("MainWindow", "Please_1", None))
        self.comboBox.setItemText(8, _translate("MainWindow", "Yes_1", None))
        self.comboBox.setItemText(9, _translate("MainWindow", "YouKnowWhat_1", None))
        self.comboBox.setItemText(10, _translate("MainWindow", "You_1", None))
        self.comboBox.setItemText(11, _translate("MainWindow", "You_2", None))

from PyQt4 import phonon
